### ISSUE TITLE
Single Page or Multi Page?

### ISSUE THREAD

**Issue by jesseposner** [jesseposner/LaunchPad#3]
@Chebotarev I'm considering altering my component hierarchy so that every component belongs to a single "App" parent component for the entire website. It seems like this might make it a little easier to manage state by being able to pass props to any of the components, such as the log-in status of the current user.

Do you have any suggestions for weighing the pros and cons of an entirely single page architecture solely routed by the React router from one page (i.e. "/") versus a few core pages routed by Rails with different root React components for each page (i.e. "/" page for the SplashCarouselApp, "/explore" page for the BrowserApp, "/explore/:id" page for the CompanyDetailApp, and "/launch" page for the FormApp)?

**Comment by Chebotarev** [comment]
I think it's a great idea to rework your component hierarchy to only use a single page! In fact, I think I glazed over that you didn't have that before or I would have recommended it. It will be easier to manage state that way, and you can use your Rails backend almost exclusively as an api for your database. Having multiple page apps has the advantage that you don't need to load as much javascript when the user first comes onto your page. So if you were to scale up your app to a larger user base, it might make sense to break up into different pages so that each one would load faster. I believe that's part of what facebook does to handle it's massive  traffic. For your app, single page would be excellent. The `App` component also provides a great place to put content you might want  on all your "pages" (like your navbar). Hope this helps!

**Comment by jesseposner** [comment]
Thank you Alex, that is super helpful and fully addresses my question.
